# Dockerc compose only for developing purpose

version: "3.8"

services:
  couchdb:
    build:
      context: ./couchdb
      dockerfile: Dockerfile
    container_name: hr_couchdb
    ports:
      - "5990:5990"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  dbinit:
    image: curlimages/curl
    container_name: hr_couchdb_init
    depends_on:
      - couchdb
    command: >
      sh -c
      "sleep 5s &&
      curl -X PUT http://admin:password@couchdb:5990/_global_changes &&
      curl -X PUT http://admin:password@couchdb:5990/_users/_security -d '{}' &&
      curl -X PUT http://admin:password@couchdb:5990/hospitalrun?partitioned=false &&
      curl -X PUT http://admin:password@couchdb:5990/hospitalrun/_security -d '{\"members\": {}, \"admins\": {\"roles\": [\"_admin\"] }}' &&
      curl -X PUT http://admin:password@couchdb:5990/_users/org.couchdb.user:username -H \"Accept: application/json\" -H \"Content-Type: application/json\" -d '{\"name\": \"username\", \"password\": \"password\", \"metadata\": { \"givenName\": \"John\", \"familyName\": \"Doe\"}, \"roles\": [], \"type\": \"user\"}'"
