site_name: HIMS
site_url: https://hims.prod.innoht.live/
site_description: Inno HIMS project documentation
site_author: Inno HIMS Core Team

repo_url: https://git.innoht.live/innohealthtech/hims/

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
